In [4]:
!pip install metric_learn
from datapreparation.profile_parser import *
import metric_learn

Requirement already satisfied: metric_learn in /Users/sswetank/anaconda3/lib/python3.6/site-packages (0.4.0)
Requirement already satisfied: six in /Users/sswetank/anaconda3/lib/python3.6/site-packages (from metric_learn) (1.12.0)
Requirement already satisfied: scikit-learn in /Users/sswetank/anaconda3/lib/python3.6/site-packages (from metric_learn) (0.20.2)
Requirement already satisfied: scipy in /Users/sswetank/anaconda3/lib/python3.6/site-packages (from metric_learn) (1.2.1)
Requirement already satisfied: numpy in /Users/sswetank/anaconda3/lib/python3.6/site-packages (from metric_learn) (1.16.2)

In [ ]:
import pandas as pd

In [ ]:
df_acc=pd.read_json('data/account.json')

In [ ]:
len(df_acc['Name'].unique())

In [ ]:
df_acc[df_acc['Name']=='SOFTBANK ROBOTICS EUROPE']

In [ ]:
df_opp=pd.read_json('data/oppurtunity.json')

In [ ]:
df_opp

In [ ]:
df_opp[df_opp['AccountId']=='001o000000c7KnDAAU']

In [ ]:
# Find similar opportunities to a given opportunity

In [ ]:
# Data preparation 
# 1.Cleanse opportunity names
# 2.Convert categorical data to dummies

In [ ]:
df_opp.columns

In [ ]:
opp_names=df_opp['Name']
print(len(opp_names))
print(len(opp_names.unique()))
first_names=pd.Series([name.split('-')[0].strip() for name in opp_names.unique()])
print(len(first_names.unique()))
print(first_names.unique())
opp_names

In [ ]:
opp_names

In [ ]:
# Read data from cortex managed content

import requests

headers={'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjb2duaXRpdmVzY2FsZS5jb20iLCJhdWQiOiJjb3J0ZXgiLCJzdWIiOiJzc3dldGFuayIsInRlbmFudCI6ImNvcnRleC1hY2NlbGVyYXRvcnMiLCJiZWFyZXIiOiJwdWJsaWMiLCJrZXkiOiI0dk9zRVRFZFJtazl0T0NFdUV4UnRsdEVuVllnck9VdiIsImV4cCI6MTU4OTUxMjM0MywiYWNsIjp7Ii4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSIsIkRFTEVURSJdLCIvdjMvYWdlbnRzL2Vudmlyb25tZW50cy8uKiI6WyJERU5ZIl0sIi92Mi9hZG1pbi8uKiI6WyJERU5ZIl0sIi92Mi90ZW5hbnRzL2N1cnJlbnQtdXNlci1kZXRhaWxzIjpbIlJFQUQiXSwiL3YyL2FjY291bnRzLy4qIjpbIkRFTlkiXSwiL3YyL3RlbmFudHMvLioiOlsiREVOWSJdLCIvdjIvYWNjb3VudHMvdG9rZW5zLy4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSJdLCIvdjIvdGVuYW50cy9zZWNyZXRzLy4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSJdLCIvdjMvYWdlbnRzL2Vudmlyb25tZW50cy9jb3J0ZXgvZGVmYXVsdCI6WyJSRUFEIiwiUlVOIiwiV1JJVEUiXSwiL3YzL2NhdGFsb2cvLioiOlsiUkVBRCIsIlJVTiIsIldSSVRFIiwiREVMRVRFIl19LCJpYXQiOjE1NTc5NzYzNDN9.U8PBzBHo8QfGgwCtJuQOoUufggOxtfaNSj2uwpgfoXc'}
cleansed_data=requests.get('https://api.cortex.insights.ai/v2/content/acceleartors/profile-similarity/profilesimilarity.csv',headers=headers)
cleansed_data.text

In [ ]:
from io import StringIO

cleansed_data_df=pd.read_csv(StringIO(cleansed_data.text))

In [ ]:
cleansed_data_df

In [ ]:
def get_cleansed_df(managed_content_path, token):
    from io import StringIO
    import requests
    headers={'Authorization': 'Bearer {}'.format(token)}
    cleansed_data=requests.get(managed_content_path,headers=headers)
    cleansed_data_df=pd.read_csv(StringIO(cleansed_data.text))
    return cleansed_data_df
    
token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjb2duaXRpdmVzY2FsZS5jb20iLCJhdWQiOiJjb3J0ZXgiLCJzdWIiOiJzc3dldGFuayIsInRlbmFudCI6ImNvcnRleC1hY2NlbGVyYXRvcnMiLCJiZWFyZXIiOiJwdWJsaWMiLCJrZXkiOiI0dk9zRVRFZFJtazl0T0NFdUV4UnRsdEVuVllnck9VdiIsImV4cCI6MTU4OTUxMjM0MywiYWNsIjp7Ii4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSIsIkRFTEVURSJdLCIvdjMvYWdlbnRzL2Vudmlyb25tZW50cy8uKiI6WyJERU5ZIl0sIi92Mi9hZG1pbi8uKiI6WyJERU5ZIl0sIi92Mi90ZW5hbnRzL2N1cnJlbnQtdXNlci1kZXRhaWxzIjpbIlJFQUQiXSwiL3YyL2FjY291bnRzLy4qIjpbIkRFTlkiXSwiL3YyL3RlbmFudHMvLioiOlsiREVOWSJdLCIvdjIvYWNjb3VudHMvdG9rZW5zLy4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSJdLCIvdjIvdGVuYW50cy9zZWNyZXRzLy4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSJdLCIvdjMvYWdlbnRzL2Vudmlyb25tZW50cy9jb3J0ZXgvZGVmYXVsdCI6WyJSRUFEIiwiUlVOIiwiV1JJVEUiXSwiL3YzL2NhdGFsb2cvLioiOlsiUkVBRCIsIlJVTiIsIldSSVRFIiwiREVMRVRFIl19LCJpYXQiOjE1NTc5NzYzNDN9.U8PBzBHo8QfGgwCtJuQOoUufggOxtfaNSj2uwpgfoXc'
managed_content_path='https://api.cortex.insights.ai/v2/content/acceleartors/profile-similarity/profilesimilarity.csv'
cleansed_df=get_cleansed_df(managed_content_path,token)

In [ ]:
import json
import requests
import pandas as pd

def get_profile_data(url, token,profile_id):    
    data={"payload":{"profile_id":profile_id ,"profile_schema_and_version": "cortex/TestAccount"}}
    data=json.dumps(data)
#     print(data)
    headers={'Content-Type': 'application/json','Authorization': 'Bearer {}'.format(token)}
#     print(headers)
    activation_data=requests.post(url,headers=headers,data=data).json()
#     print(activation_data)
#     activation_data=json.loads(activation_data)
#     print(activation_data)
#     print(activation_data['success'])
#     print(activation_data['activationId'])
    if activation_data['success']:
        activation_id=activation_data['activationId']
        profile_data=requests.get('https://api.cortex.insights.ai/v3/agents/services/activations/'+str(activation_id),headers=headers).json()
#     return json.loads(profile_data)
    return profile_data

def get_attributes(profile_data):
    a=[[attr['attributeValue']['value']] for attr in profile_data['activation']['response']['profile']['attributes']]
    df = pd.DataFrame(a)
    df2 = df.T
    df2.columns = ['Sentiment','Entities','Tone','Industry','Competitors','Opportunity','Topics','AccountName','Contacts']
    return df2
    
    
token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjb2duaXRpdmVzY2FsZS5jb20iLCJhdWQiOiJjb3J0ZXgiLCJzdWIiOiJzc3dldGFuayIsInRlbmFudCI6ImNvcnRleC1hY2NlbGVyYXRvcnMiLCJiZWFyZXIiOiJwdWJsaWMiLCJrZXkiOiI0dk9zRVRFZFJtazl0T0NFdUV4UnRsdEVuVllnck9VdiIsImV4cCI6MTU4OTUxMjM0MywiYWNsIjp7Ii4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSIsIkRFTEVURSJdLCIvdjMvYWdlbnRzL2Vudmlyb25tZW50cy8uKiI6WyJERU5ZIl0sIi92Mi9hZG1pbi8uKiI6WyJERU5ZIl0sIi92Mi90ZW5hbnRzL2N1cnJlbnQtdXNlci1kZXRhaWxzIjpbIlJFQUQiXSwiL3YyL2FjY291bnRzLy4qIjpbIkRFTlkiXSwiL3YyL3RlbmFudHMvLioiOlsiREVOWSJdLCIvdjIvYWNjb3VudHMvdG9rZW5zLy4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSJdLCIvdjIvdGVuYW50cy9zZWNyZXRzLy4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSJdLCIvdjMvYWdlbnRzL2Vudmlyb25tZW50cy9jb3J0ZXgvZGVmYXVsdCI6WyJSRUFEIiwiUlVOIiwiV1JJVEUiXSwiL3YzL2NhdGFsb2cvLioiOlsiUkVBRCIsIlJVTiIsIldSSVRFIiwiREVMRVRFIl19LCJpYXQiOjE1NTc5NzYzNDN9.U8PBzBHo8QfGgwCtJuQOoUufggOxtfaNSj2uwpgfoXc'
url="https://api.cortex.insights.ai/v3/agents/c360/customer-360-toplevel/services/retrieve-profile"
profile_id="001o000000f514aAAA"
profile_data=get_profile_data(url,token,profile_id)
# print(pd.read_json(json.dumps(profile_data['activation']['response']['profile']['attributes'])))
# print(json.dumps(profile_data))
# attrs=profile_data['activation']['response']['profile']['attributes']
# print(attrs)

for opp in get_attributes(profile_data)['Opportunity']:
    for o in opp:
        print(o)

In [ ]:
attrs_df=get_attributes(profile_data)
attrs_df['Contacts'][0]

In [ ]:
# pd.get_dummies(attrs_df['Competitors'])

In [ ]:
tmp=pd.get_dummies(pd.Series(attrs_df['Competitors'][0]))

In [ ]:
tmp.columns=['Competitors_Francotyp', 'Competitors_Hp', 'Competitors_One Stop Systems', 'Competitors_Quantum', 'Competitors_SuperMicro']

In [ ]:
tmp

In [ ]:
!cp /Users/sswetank/Downloads/accountdata4.csv data/

In [31]:
import numpy as np
account_df=pd.read_csv('data/accountdata4.csv')
list(account_df.columns)
df=account_df.copy()
# type(df['contacts'][0])
np.unique(df['Amount1'])
account_df.head()

,Amount1,account_name,contacts,profile_id,competitors_AIG,competitors_Aetna,competitors_Albertsons Cos.,competitors_Alphabet,competitors_AmerisourceBergen,competitors_Anthem,...,industry_name_Motor Vehicles and Parts,industry_name_Network and Other Communications Equipment,industry_name_Petroleum Refining,industry_name_Pharmaceuticals,industry_name_Pipelines,industry_name_Semiconductors and Other Electronic Components,industry_name_Specialty Retailers: Other,industry_name_Telecommunications,industry_name_Wholesalers: Food and Grocery,industry_name_Wholesalers: Health Care
0,50000,Walmart,['Eduardo Brayner'],0015I11484m7u87wBuD,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10580000,Exxon Mobil,['Ridwan Zurawik'],0017K23751y0u72fZpZ,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,21483000,Berkshire Hathaway,['Courtney Bodey'],0017O90702b2u22mRuO,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10089000,Apple,['Axel Whitsel'],0014B28932p5u37rWgX,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9141000,UnitedHealth Group,['John Santelli'],0015R72262j6u33kWxP,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [32]:
df=account_df.copy()
df=df[df.Amount1!='Engage - Enterprise(Conversational AI)']
df.Amount1=pd.to_numeric(df.Amount1)
df.head()

,Amount1,account_name,contacts,profile_id,competitors_AIG,competitors_Aetna,competitors_Albertsons Cos.,competitors_Alphabet,competitors_AmerisourceBergen,competitors_Anthem,...,industry_name_Motor Vehicles and Parts,industry_name_Network and Other Communications Equipment,industry_name_Petroleum Refining,industry_name_Pharmaceuticals,industry_name_Pipelines,industry_name_Semiconductors and Other Electronic Components,industry_name_Specialty Retailers: Other,industry_name_Telecommunications,industry_name_Wholesalers: Food and Grocery,industry_name_Wholesalers: Health Care
0,50000,Walmart,['Eduardo Brayner'],0015I11484m7u87wBuD,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10580000,Exxon Mobil,['Ridwan Zurawik'],0017K23751y0u72fZpZ,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,21483000,Berkshire Hathaway,['Courtney Bodey'],0017O90702b2u22mRuO,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10089000,Apple,['Axel Whitsel'],0014B28932p5u37rWgX,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9141000,UnitedHealth Group,['John Santelli'],0015R72262j6u33kWxP,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [33]:
for col in df.columns:
#     print(df[col].dtype)
    if df[col].dtype=='object':
#         print('Dropped col {}'.format(col))
        df.drop(col,axis=1,inplace=True)
df.head()

,Amount1,competitors_AIG,competitors_Aetna,competitors_Albertsons Cos.,competitors_Alphabet,competitors_AmerisourceBergen,competitors_Anthem,competitors_Archer Daniels Midland,competitors_Bank of America Corp.,competitors_Best Buy,...,industry_name_Motor Vehicles and Parts,industry_name_Network and Other Communications Equipment,industry_name_Petroleum Refining,industry_name_Pharmaceuticals,industry_name_Pipelines,industry_name_Semiconductors and Other Electronic Components,industry_name_Specialty Retailers: Other,industry_name_Telecommunications,industry_name_Wholesalers: Food and Grocery,industry_name_Wholesalers: Health Care
0,50000,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10580000,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,21483000,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10089000,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9141000,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn import preprocessing
amt=df.Amount1
amt=amt.values.reshape(-1,1)
scaler = preprocessing.StandardScaler().fit(amt)
# scaler.transform(amt)

In [ ]:
df['Amount1']=((df.Amount1-df.Amount1.mean()).abs())/(df.Amount1.std())

In [ ]:
df.head()

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=30)
df2=pca.fit_transform(df)

In [ ]:
df2=pd.DataFrame(df2)
df2.iloc[0:10]

In [ ]:
# np.set_printoptions(precision=3)

sim=cosine_similarity(df2[0:1],df2)
print(sim)
print(np.where(sim>=0.5))
print(sim[0][36])
# print(np.around(sim[0],50))
6.57*np.exp(-1)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import PCA


def similarity_scorer(cleansed_data,profileId,threshold,pca=False,includeAmount=False):
    account_df=pd.read_csv('data/accountdata4.csv')
    profile_data=account_df[account_df['profile_id']==profileId]
    profile_index=np.where(account_df['profile_id']==profileId)
    
    df=account_df.copy()
    
    if includeAmount:
        #This check should go in data cleansing
        df=df[df.Amount1!='Engage - Enterprise(Conversational AI)']
        df.Amount1=pd.to_numeric(df.Amount1)
        df.Amount1=((df.Amount1-df.Amount1.mean()).abs())/(df.Amount1.std())
    
    for col in df.columns:
        if df[col].dtype=='object':
            df.drop(col,axis=1,inplace=True)
    if pca:
        pca = PCA(n_components=30)
        df2=pca.fit_transform(df)

        df2=pd.DataFrame(df2)
        sim=cosine_similarity(df2.iloc[profile_index],df2)
    else:
        sim=cosine_similarity(df[0:1],df)

    indices=np.where(sim>=threshold)

    ind=[]
    for index in indices[1]: 
        ind.append(index)

    similarity_scores={}
    for i in ind:
        similarity_scores[account_df.iloc[i]['profile_id']]=sim[0][i]
    
    return sorted(similarity_scores.items(), key=lambda kv: kv[1],reverse=True)

# Profile Similarity

#### Params
1. Managed content file for cleaned up profile data
2. Profile ID for the account for which we need to check similarity
3. Similarity threshold
4. PCA boolean Flag
5. Numeric/Dense column Flag

#### Response
1. Array of tuples with profile_id and similarity scores in sorted order

#### Next steps
1. Currently data distribution is assumed Gaussian
2. Does not perform well with a dense column (amount field). Need to check how to mix sparse matrix with dense column
3. Need a supervised approach to separate disparate data points
4. Need to include inferred attributes like entities, sentiments, topics and tone from Notes data (Once it is available)

#### Load original data

In [ ]:
df_original=pd.read_csv('/Users/sswetank/Downloads/accountdata3.csv')

In [ ]:
df_original.head()

#### Data Transformations

In [ ]:
account_df.head()

## Similarity scores

#### Walmart

In [ ]:
similarity_scorer('data/accountdata4.csv','0015I11484m7u87wBuD',0.5,True)

In [ ]:
df_original[df_original['profile_id']=='0015I11484m7u87wBuD']

In [ ]:
df_original[df_original['profile_id']=='0018K30946c0u64tLmE']

In [ ]:
df_original[df_original['profile_id']=='0019L27831f6u45aPfV']

#### With Amount field included

In [ ]:
similarity_scorer('data/accountdata4.csv','0015I11484m7u87wBuD',0.5,True,True)

In [ ]:
df_original[df_original['profile_id']=='0015I11484m7u87wBuD']

In [ ]:
df_original[df_original['profile_id']=='0019T41222u0u98vUbS']

In [ ]:
df_original[df_original['profile_id']=='0018K02320f6u19yGvF']

#### Berkshire Hathaway

In [ ]:
similarity_scorer('data/accountdata4.csv','0017O90702b2u22mRuO',0.5,True)

In [ ]:
df_original[df_original['profile_id']=='0017O90702b2u22mRuO']

In [ ]:
df_original[df_original['profile_id']=='0012S45318b8u92fVzB']

In [ ]:
df_original[df_original['profile_id']=='0013B55715x9u43zCnH']

In [ ]:
df_original[df_original['profile_id']=='0014W44938l8u40sVqG']

#### UnitedHealth Group

In [ ]:
similarity_scorer('data/accountdata4.csv','0015R72262j6u33kWxP',0.5,True)

In [ ]:
df_original[df_original['profile_id']=='0015R72262j6u33kWxP']

In [ ]:
df_original[df_original['profile_id']=='0014W44938l8u40sVqG']

### Data Preparations

In [5]:
# visualisation imports
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [6]:
def plot(X, Y, i, j, label1, label2):
    x_min, x_max = X[:, i].min() - .5, X[:, i].max() + .5
    y_min, y_max = X[:, j].min() - .5, X[:, j].max() + .5
    plt.figure(2, figsize=(8, 6))

    # clean the figure
    plt.clf()

    plt.scatter(X[:, i], X[:, j], c=Y, cmap=plt.cm.Paired)
    plt.xlabel(label1)
    plt.ylabel(label2)

    plt.xlim(x_min, x_max)
    plt.ylim(y_min, y_max)
    plt.xticks(())
    plt.yticks(())

    plt.show()

In [34]:
from metric_learn import LMNN
lmnn = LMNN(k=5, learn_rate=1e-6)

lmnn.fit(X, Y)
X_lmnn = lmnn.transform()

plot(X_lmnn,Y,0,1,"Sepal Length", "Sepal Width")
plot(X_lmnn,Y,2,3,"Petal Length", "Petal Width")
plot(X_lmnn,Y,0,2,"Sepal Length", "Petal Length")
plot(X_lmnn,Y,0,3,"Sepal Length", "Petal Width")
plot(X_lmnn,Y,1,2,"Sepal Width", "Petal Length")
plot(X_lmnn,Y,1,3,"Sepal Width", "Petal Width")

NameError: name 'X' is not defined

In [50]:
from datapreparation.profile_parser import *
token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjb2duaXRpdmVzY2FsZS5jb20iLCJhdWQiOiJjb3J0ZXgiLCJzdWIiOiJzc3dldGFuayIsInRlbmFudCI6ImNvcnRleC1hY2NlbGVyYXRvcnMiLCJiZWFyZXIiOiJwdWJsaWMiLCJrZXkiOiI0dk9zRVRFZFJtazl0T0NFdUV4UnRsdEVuVllnck9VdiIsImV4cCI6MTU5MTY5MzE4OCwiYWNsIjp7Ii4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSIsIkRFTEVURSJdLCIvdjMvYWdlbnRzL2Vudmlyb25tZW50cy8uKiI6WyJERU5ZIl0sIi92Mi90ZW5hbnRzL2N1cnJlbnQtdXNlci1kZXRhaWxzIjpbIlJFQUQiXSwiL3YyL2FkbWluLy4qIjpbIkRFTlkiXSwiL3YyL2FjY291bnRzLy4qIjpbIkRFTlkiXSwiL3YyL3RlbmFudHMvLioiOlsiREVOWSJdLCIvdjIvYWNjb3VudHMvdG9rZW5zLy4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSJdLCIvdjIvdGVuYW50cy9zZWNyZXRzLy4qIjpbIlJFQUQiLCJSVU4iLCJXUklURSJdLCIvdjMvYWdlbnRzL2Vudmlyb25tZW50cy9jb3J0ZXgvZGVmYXVsdCI6WyJSRUFEIiwiUlVOIiwiV1JJVEUiXSwiL3YzL2NhdGFsb2cvLioiOlsiUkVBRCIsIlJVTiIsIldSSVRFIiwiREVMRVRFIl19LCJpYXQiOjE1NjAxNTcxODh9.oqypuJ22neeuzzhJ_0XEG3OYJOhyMcWJU35uIbaZugw'
url="https://api.cortex.insights.ai/v3/agents/c360/customer-360-toplevel/services/retrieve-profile"
final_list=parse_profile_data(url,token)
print('Parsing complete')
original_df = pd.DataFrame(final_list)
original_df['Amount1']=original_df.apply(remove_text, axis=1)

final_df=get_df_competitors(original_df)

final_df_with_dummies = pd.get_dummies( final_df, columns = ['competitor_names','ExecSponsor1','OpportunityName1','OpportunityStatus1','industry_name'] )
# final_df_with_dummies.to_csv("profiledata.csv", sep=',', index=False,encoding='utf-8')

Parsing complete

In [51]:
industries=final_df['industry_name']

from  sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
# print(le.fit_transform(industries))
# print(industries)

target=le.fit_transform(industries)
final_df_with_dummies['Target']=target
final_df_with_dummies.head()

,Amount1,account_name,contacts,profile_id,competitor_names_AIG,competitor_names_AT&T,competitor_names_Aetna,competitor_names_Albertsons Cos.,competitor_names_Alphabet,competitor_names_Amazon.com,...,industry_name_Network and Other Communications Equipment,industry_name_Petroleum Refining,industry_name_Pharmaceuticals,industry_name_Pipelines,industry_name_Semiconductors and Other Electronic Components,industry_name_Specialty Retailers: Other,industry_name_Telecommunications,industry_name_Wholesalers: Food and Grocery,industry_name_Wholesalers: Health Care,Target
0,50000,Walmart,[Eduardo Brayner],0015I11484m7u87wBuD,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
1,50000,Costco,[Karim Krzan],0011S65285x2u62kQjM,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
2,50000,Target,[Michael McNamara],0018K30946c0u64tLmE,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
3,10580000,Exxon Mobil,[Ridwan Zurawik],0017K23751y0u72fZpZ,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,27
4,50000,Chevron,[David Seals],0010V22883q6u92eKgN,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,27

In [142]:
final_df.head()

,Amount1,ExecSponsor1,OpportunityName1,OpportunityStatus1,account_name,competitor_names,contacts,industry_name,profile_id
0,50000,Rosella Hymer,Amplify - QuickStart(Process Insights),Confirming Value with Power,Walmart,Costco,[Eduardo Brayner],General Merchandisers,0015I11484m7u87wBuD
1,50000,Axel Whitsel,Engage - QuickStart(Coversational AI),Prospecting,Costco,Target,[Karim Krzan],General Merchandisers,0011S65285x2u62kQjM
2,50000,Jayne Knox,Amplify - QuickStart(Process Insights),Confirming Value with Power,Target,Walmart,[Michael McNamara],General Merchandisers,0018K30946c0u64tLmE
3,10580000,Astrid Schmaus,Amplify - Enterprise(Survellance Insights),Use Case Confirmed,Exxon Mobil,Chevron,[Ridwan Zurawik],Petroleum Refining,0017K23751y0u72fZpZ
4,50000,Olly Breuninger,Amplify - QuickStart(Survellance Insights),Use Case Confirmed,Chevron,Phillips 66,[David Seals],Petroleum Refining,0010V22883q6u92eKgN

In [141]:
final_df_with_dummies.head()

,Amount1,account_name,contacts,profile_id,competitor_names_AIG,competitor_names_AT&T,competitor_names_Aetna,competitor_names_Albertsons Cos.,competitor_names_Alphabet,competitor_names_Amazon.com,...,industry_name_Network and Other Communications Equipment,industry_name_Petroleum Refining,industry_name_Pharmaceuticals,industry_name_Pipelines,industry_name_Semiconductors and Other Electronic Components,industry_name_Specialty Retailers: Other,industry_name_Telecommunications,industry_name_Wholesalers: Food and Grocery,industry_name_Wholesalers: Health Care,Target
0,50000,Walmart,[Eduardo Brayner],0015I11484m7u87wBuD,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
1,50000,Costco,[Karim Krzan],0011S65285x2u62kQjM,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
2,50000,Target,[Michael McNamara],0018K30946c0u64tLmE,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
3,10580000,Exxon Mobil,[Ridwan Zurawik],0017K23751y0u72fZpZ,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,27
4,50000,Chevron,[David Seals],0010V22883q6u92eKgN,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,27

In [166]:
df=final_df_with_dummies.copy()
df.Amount1=pd.to_numeric(df.Amount1)
df.Amount1=((df.Amount1-df.Amount1.mean()).abs())/(df.Amount1.std())


for col in df.columns:
    if df[col].dtype=='object':
        df.drop(col,axis=1,inplace=True)

Y=df.Target
X=df.drop('Target',axis=1)
Y.head()

0    12
1    12
2    12
3    27
4    27
Name: Target, dtype: int64

In [167]:
df.head()

,Amount1,competitor_names_AIG,competitor_names_AT&T,competitor_names_Aetna,competitor_names_Albertsons Cos.,competitor_names_Alphabet,competitor_names_Amazon.com,competitor_names_American Airlines Group,competitor_names_AmerisourceBergen,competitor_names_Anthem,...,industry_name_Network and Other Communications Equipment,industry_name_Petroleum Refining,industry_name_Pharmaceuticals,industry_name_Pipelines,industry_name_Semiconductors and Other Electronic Components,industry_name_Specialty Retailers: Other,industry_name_Telecommunications,industry_name_Wholesalers: Food and Grocery,industry_name_Wholesalers: Health Care,Target
0,0.503836,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
1,0.503836,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
2,0.503836,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
3,0.339493,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,27
4,0.503836,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,27

In [168]:
X.head()

,Amount1,competitor_names_AIG,competitor_names_AT&T,competitor_names_Aetna,competitor_names_Albertsons Cos.,competitor_names_Alphabet,competitor_names_Amazon.com,competitor_names_American Airlines Group,competitor_names_AmerisourceBergen,competitor_names_Anthem,...,industry_name_Motor Vehicles and Parts,industry_name_Network and Other Communications Equipment,industry_name_Petroleum Refining,industry_name_Pharmaceuticals,industry_name_Pipelines,industry_name_Semiconductors and Other Electronic Components,industry_name_Specialty Retailers: Other,industry_name_Telecommunications,industry_name_Wholesalers: Food and Grocery,industry_name_Wholesalers: Health Care
0,0.503836,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.503836,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.503836,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.339493,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0.503836,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [171]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import PCA


def similarity_scorer(x,original_df,profile_id,threshold,pca=False,includeAmount=False): 
    x=x.copy()
    profile_index=np.where(original_df['profile_id']==profile_id)
    profile_data=x.iloc[profile_index]
    
    if not includeAmount:
        x.drop('Amount1',axis=1,inplace=True)
        profile_data.drop('Amount1',axis=1,inplace=True)
        
    if pca:
        pca = PCA(n_components=30)
        df2=pca.fit_transform(x)

        df2=pd.DataFrame(df2)
        sim=cosine_similarity(df2.iloc[profile_index],df2)
    else:
        sim=cosine_similarity(profile_data,x)

    indices=np.where(sim[0]>=threshold)

    similarity_scores={}
    for i in indices[0]:
        similarity_scores[original_df.iloc[i]['profile_id']]=sim[0][i]
    
    print(similarity_scores)
    return sorted(similarity_scores.items(), key=lambda kv: kv[1],reverse=True)

In [175]:
similarity_scorer(X,final_df,'0015I11484m7u87wBuD',0.5,True,False)

{'0015I11484m7u87wBuD': 0.9999999999999999, '0018K30946c0u64tLmE': 0.7756545909505524, '0019L27831f6u45aPfV': 0.5212273493230966}

/Users/sswetank/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

[('0015I11484m7u87wBuD', 0.9999999999999999),
 ('0018K30946c0u64tLmE', 0.7756545909505524),
 ('0019L27831f6u45aPfV', 0.5212273493230966)]

In [173]:
final_df[final_df['profile_id']=='0015I11484m7u87wBuD']

,Amount1,ExecSponsor1,OpportunityName1,OpportunityStatus1,account_name,competitor_names,contacts,industry_name,profile_id
0,50000,Rosella Hymer,Amplify - QuickStart(Process Insights),Confirming Value with Power,Walmart,Costco,[Eduardo Brayner],General Merchandisers,0015I11484m7u87wBuD

In [174]:
final_df[final_df['profile_id']=='0018K30946c0u64tLmE']

,Amount1,ExecSponsor1,OpportunityName1,OpportunityStatus1,account_name,competitor_names,contacts,industry_name,profile_id
2,50000,Jayne Knox,Amplify - QuickStart(Process Insights),Confirming Value with Power,Target,Walmart,[Michael McNamara],General Merchandisers,0018K30946c0u64tLmE

In [176]:
final_df[final_df['profile_id']=='0019L27831f6u45aPfV']

,Amount1,ExecSponsor1,OpportunityName1,OpportunityStatus1,account_name,competitor_names,contacts,industry_name,profile_id
39,50000,Olly Breuninger,Amplify - QuickStart(Process Insights),Confirming Value with Power,Wells Fargo,Citigroup,[Mark Hammersmith],Commercial Banks,0019L27831f6u45aPfV